### ISSUE TITLE
Some wrong typo in run_transductive_cnaps_mt.py

### ISSUE THREAD

**Issue by jiyang91** [plai-group/simple-cnaps#6]
Hi, I have tested this good organized source for my dataset.
But, there was some typo in run_transductive_cnaps_mt.py(https://github.com/peymanbateni/simple-cnaps/blob/4e9609b202d52df57dd8d2931bd16a914c8099f8/transductive-cnaps-src/run_transductive_cnaps_mt.py).

In line 146, 158, "max_cluster_refinement_step_test" need to be "max_cluster_refinement_step**s**_test" or, it makes error when I tested this source.

If it is right, can you add 's'?

**Comment by peymanbateni** [comment]
Hi Jiyang,

Glad to hear you are finding the repo useful. Thanks a lot for pointing this typo out. You are absolutely right! 

Surprisingly, the simple print outs were not there when we were running the final tests on the code, and therefore, it was missed. It was also the case in run_transductive_cnaps.py. I have fixed it across both the plai-group and my personal github copies of the simple-cnaps repo.

Thanks again for pointing these out. I'll close the issue for now, but if there is anything else, please don't hesitate to make a new issue on it and I'll get to it as soon as possible.

Best,
Peyman
